### ISSUE TITLE
Plugin breaks when Bluemap is reloaded

### ISSUE THREAD

**Issue by FlorianFreudiger** [tpwalke2/BlueMapSignMarkers#50]
Plugins works great until Bluemap is reloaded via `bluemap reload`.

The markers disappear and the following exception is logged:
```java
[Thread-20/INFO]: WebServer started.
[BlueMap-Plugin-ReloadCommand/ERROR]: BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@67a0e838[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@69852910[Wrapped task = com.tpwalke2.bluemapsignmarkers.core.reactive.ReactiveQueue$$Lambda/0x00007f79f4e0fdc8@595f5c6a]] rejected from java.util.concurrent.ThreadPoolExecutor@11703ff2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:?]
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:?]
        at com.tpwalke2.bluemapsignmarkers.core.reactive.ReactiveQueue.process(ReactiveQueue.java:32) ~[bluemapsignmarkers-1.20.1-0.1.1.10.jar:?]
        at com.tpwalke2.bluemapsignmarkers.core.bluemap.BlueMapAPIConnector.onEnable(BlueMapAPIConnector.java:97) ~[bluemapsignmarkers-1.20.1-0.1.1.10.jar:?]
        at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:211) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:175) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:351) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:112) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:465) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$reloadCommand$5(Commands.java:398) ~[BlueMap-3.20-fabric-1.20.jar:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

Tested with version 1.20.1-0.1.1.10 and both Bluemap version 3.20 and snapshot version 4.1

**Comment by tpwalke2** [comment]
@FlorianFreudiger, thank you for reporting this. I was out of town on vacation this past week but now have a fix pushed to the main branch. My token for authenticating with Modrinth in order to upload a release has expired and there is a bug that has broken their personal access token page (https://github.com/modrinth/knossos/issues/1680). Once they have fixed the site, I'll generate a new token and get a release posted.

**Comment by tpwalke2** [comment]
@FlorianFreudiger, I have published the updated version to Modrinth here: https://modrinth.com/mod/bluemap-sign-markers/version/1.20.1-0.1.2.13

Thanks again!
