### ISSUE TITLE
Crash when loading the End

### ISSUE THREAD

**Issue by tpwalke2** [tpwalke2/BlueMapSignMarkers#53]
26.04 10:28:40 [Server] [INFO] java.util.concurrent.CompletionException: java.lang.NullPointerException
26.04 10:28:40 [Server] [INFO] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
26.04 10:28:40 [Server] [INFO] at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
26.04 10:28:40 [Server] [INFO] at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
26.04 10:28:40 [Server] [INFO] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
26.04 10:28:40 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
26.04 10:28:40 [Server] [INFO] Caused by: java.lang.NullPointerException
26.04 10:28:40 [Server] [INFO] at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
26.04 10:28:40 [Server] [INFO] at java.util.TreeMap.getEntry(TreeMap.java:345) ~[?:?]
26.04 10:28:40 [Server] [INFO] at java.util.TreeMap.get(TreeMap.java:279) ~[?:?]
26.04 10:28:41 [Server] [INFO] at com.tpwalke2.bluemapsignmarkers.core.signs.SignManager.addOrUpdateSign(SignManager.java:128) ~[bluemapsignmarkers-1.20.1-0.2.0.14-alpha.jar:?]
26.04 10:28:41 [Server] [INFO] at com.tpwalke2.bluemapsignmarkers.core.signs.SignManager.addOrUpdate(SignManager.java:25) ~[bluemapsignmarkers-1.20.1-0.2.0.14-alpha.jar:?]
26.04 10:28:41 [Server] [INFO] at com.tpwalke2.bluemapsignmarkers.BlueMapSignMarkersMod.onBlockEntityLoad(BlueMapSignMarkersMod.java:45) ~[bluemapsignmarkers-1.20.1-0.2.0.14-alpha.jar:?]
26.04 10:28:41 [Server] [INFO] at net.fabricmc.fabric.api.event.lifecycle.v1.ServerBlockEntityEvents.lambda$static$0(ServerBlockEntityEvents.java:37) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-64bb13225b65065c.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_2818.handler$zdp000$fabric-lifecycle-events-v1$onLoadBlockEntity(class_2818.java:1758) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_2818.method_12007(class_2818.java:377) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_2852.method_39797(class_2852.java:410) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
26.04 10:28:41 [Server] [INFO] at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
26.04 10:28:41 [Server] [INFO] at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
26.04 10:28:41 [Server] [INFO] at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[server-intermediary.jar:?]
26.04 10:28:41 [Server] [INFO] at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]

**Comment by tpwalke2** [comment]
Fixed in https://modrinth.com/mod/bluemap-sign-markers/version/1.20.1-0.2.3.20
